# site properties and page defaults
title: VPEC Lab
subtitle:
description: In the Visual Perception, Emotion & Cognition (VPEC) Laboratory, we study visual perception. Our primary goal is to understand how basic neural and cognitive mechanisms shape what people see and hear. We also collaborate to examine the role of perceptual processes in clinical, affective and social outcomes.
# logo-text: VPEC Lab
header: images/background.jpg
footer: images/background.jpg

# site social media and other links
links:
  email: timothy.sweeny@du.edu
  orcid: 0000-0002-5602-3215
  google-scholar: iEE5bbkAAAAJ
  github: VPEC-Lab
#  twitter: anushanandd
#  youtube: anushanandd

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
