- id: doi:10.1080/02699931.2025.2506667
  buttons:
    - type: pdf
      link: documents/McDonagh_2025.pdf

- id: doi:10.1038/s41562-022-01390-y
  buttons:
    - type: pdf
      link: documents/Goldenberg_2022.pdf

- id: doi:10.1371/journal.pone.0275281
  buttons:
    - type: pdf
      link: documents/Mihalache_2022.pdf

- id: doi:10.1037/xge0001025
  buttons:
    - type: pdf
      link: documents/Mihalache_2021.pdf

- id: doi:10.1177/0956797620970561
  buttons:
    - type: pdf
      link: documents/Goldenberg_2021.pdf

- id: doi:10.3758/s13414-020-02109-9
  buttons:
    - type: pdf
      link: documents/Sweeny_APP_2020.pdf

- id: doi:10.1037/xhp0000733
  buttons:
    - type: pdf
      link: documents/Elias_2020.pdf

- id: doi:10.1037/xge0000651
  buttons:
    - type: pdf
      link: documents/Goldenberg_2020.pdf

- id: doi:10.1080/13506285.2020.1717706
  buttons:
    - type: pdf
      link: documents/Ji_2020.pdf

- id: doi:10.1111/desc.12886
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/mihalache_ds_2019.pdf

- id: doi:10.1016/j.visres.2019.01.002
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/braun_visres_2019.pdf

- id: doi:10.1037/xge0000443
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/lamer_jepg_2018.pdf

- id: doi:10.1016/j.concog.2018.03.005
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/elias_cc_2018.pdf

- id: doi:10.1016/j.ijhcs.2018.04.005
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/psych-lab-vepc-mollahosseini_2018.pdf

- id: doi:10.1177/0956797616678188
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/elias_ps_2017.pdf

- id: doi:10.1037/xge0000339
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/lamer_jepg_2017.pdf

- id: doi:10.3758/s13414-017-1381-y
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_app_2017.pdf

- id: doi:10.1016/j.visres.2016.10.014
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_vr_2017.pdf

- id: doi:10.1111/desc.12239
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_ds_2015.pdf

- id: doi:10.1177/0956797614544510
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_ps_2014.pdf

- id: doi:10.1177/0956797612473759
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/VPEC-Humans-Use-Summary-Statistics-to-Perceive-Auditory-Sequences.pdf

- id: doi:10.1037/a0029193
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_emo_2012.pdf

- id: doi:10.1037/a0028712
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_jephpp_2013.pdf

- id: doi:10.1037/a0031714
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_dp_2013.pdf

- id: doi:10.1016/j.visres.2012.05.008
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_vr_2012.pdf

- id: doi:10.3758/s13423-011-0198-2
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sherman_pbr_2012.pdf

- id: doi:10.1177/0956797611413292
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_ps_2011.pdf

- id: doi:10.1152/jn.00061.2010
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_jn_2011.pdf

- id: doi:10.1167/11.1.16
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_jov_2011.pdf

- id: doi:10.1016/j.concog.2009.07.011
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweeny_cc_2009.pdf

- id: doi:10.1167/9.3.2
  buttons:
    - type: pdf
      link: https://liberalarts.du.edu/sites/default/files/2021-04/sweenyjov2009.pdf
